executable = run.sh

optuna_n_trials = 100

output = logs/job_$(train_tag).out
error  = logs/job_$(train_tag).err
log    = logs/job_$(train_tag).log

+JobFlavour = "tomorrow"

request_cpus = 4
request_memory = 12000

arguments = $(train_tag) $(optuna_n_trials) $(search_space_tag)

queue train_tag, search_space_tag from (
  pb23v2_4v2_o100_v31 v31
  pb23v2_4v2_o100_v32 v32
  pb23v2_4v2_o100_v33 v33
  pb23v2_4v2_o100_v34 v34
  pb23v2_4v2_o100_v35 v35
  pb23v2_4v2_o100_v36 v36
  pb23v2_4v2_o100_v37 v37
  pb23v2_4v2_o100_v38 v38
  pb23v2_4v2_o100_v39 v39
  pb23v2_4v2_o100_v40 v40
)
