executable = run.sh

optuna_n_trials = 50

output = logs/job_$(train_tag).out
error  = logs/job_$(train_tag).err
log    = logs/job_$(train_tag).log

+JobFlavour = "tomorrow"

request_cpus = 4
request_memory = 12000

arguments = $(train_tag) $(optuna_n_trials) $(search_space_tag)

queue train_tag, search_space_tag from (
  pb23_4v_o100_v1 v1
  pb23_4v_o100_v2 v2
  pb23_4v_o100_v3 v3
  pb23_4v_o100_v4 v4
  pb23_4v_o100_v5 v5
  pb23_4v_o100_v6 v6
  pb23_4v_o100_v7 v7
  pb23_4v_o100_v8 v8
  pb23_4v_o100_v9 v9
  pb23_4v_o100_v10 v10
)
