executable = /bin/bash

output = logs/job_$(job_tag).out
error  = logs/job_$(job_tag).err
log    = logs/job_$(job_tag).log

+JobFlavour = "tomorrow"

request_cpus = 4
request_memory = 12000

arguments = -lc "cd /afs/cern.ch/user/l/leyao/private/pbpb_work/X_analysis/XGBoost && source .venv/bin/activate && python3 workflows/group_apply_draw.py $(group_tag) $(version_start) $(version_end) $(skip_version) $(draw_only) $(version_token) $(dataset_year) $(data_input_override) $(output_prefix) $(fid_profile)"

queue 1
