executable = /bin/bash

optuna_n_trials = $(optuna_n_trials)
resume_flag = $(resume_flag)
dataset_year = $(dataset_year)
selection_profile = $(selection_profile)

output = logs/job_$(job_tag).out
error  = logs/job_$(job_tag).err
log    = logs/job_$(job_tag).log

+JobFlavour = "tomorrow"

request_cpus = 4
request_memory = 12000

arguments = -lc "cd /afs/cern.ch/user/l/leyao/private/pbpb_work/X_analysis/XGBoost && source .venv/bin/activate && python3 workflows/train_dispatch.py $(train_tag) $(optuna_n_trials) $(stage_group) $(resume_flag) $(dataset_year) $(selection_profile)"

queue 1
