executable = /bin/bash

output = logs/job_$(job_tag).out
error  = logs/job_$(job_tag).err
log    = logs/job_$(job_tag).log

+JobFlavour = "tomorrow"

request_cpus = 4
request_memory = 12000

arguments = -lc "cd /afs/cern.ch/user/l/leyao/private/pbpb_work/X_analysis/XGBoost && source .venv/bin/activate && if [ \"$(step)\" = train ]; then python3 workflows/condor_optuna_XGBoost.py $(train_tag); elif [ \"$(step)\" = apply ]; then python3 workflows/batch_apply_scores.py $(train_tag); elif [ \"$(step)\" = draw ]; then python3 workflows/batch_draw_scores.py $(train_tag); else python3 workflows/shap_importance.py $(train_tag); fi"

queue 1
